Add Styling
faisalakb/BookStore pull request #5
Opened 2023-09-01 15:27 UTC by faisalakb

In this project apply the following features : :100: 
 - Add any missing JSX elements :+1: 
 - Final design according to Zeplin's design :+1: 
 - Use the CSS rules detailed in Zeplin to style the website.  :+1: 
 - React setup . :+1: 
 - Setup Linters . :+1:

2023-09-01 16:51 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @faisalakb  
 Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
:heavy_check_mark:  Your Work looks Professional 
:heavy_check_mark:  Nice work so far :+1: 
 
 ## Required Changes 

- [ ]  Check Under the review

 ## Optional suggestions 

- [ ] N/A
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 16:51 UTC, Alfredbis29 commented on src/App.css
- [ ] While I appreciate the effort that has gone into it, I must express my concern that the final design doesn't quite align with the original design concept provided at the outset of the project. I can see that your book title doesn't look the same as the Zeplin: the fonts and colors do not look the same as the design, kindly follow the design.
**Your Design**
![Screenshot from 2023-09-01 18-13-50](https://github.com/faisalakb/BookStore/assets/88894525/d5f2f27a-38c8-4496-a3ac-36314eb52934)

**Zeplin Design**
![Screenshot from 2023-09-01 18-14-24](https://github.com/faisalakb/BookStore/assets/88894525/fef9b3b6-7d8a-4b9d-a22b-3c1d6c02f13f)

2023-09-01 16:51 UTC, Alfredbis29 commented on src/App.css
- [ ] I've noticed that the header design doesn't quite match the original concept. Can you adjustments to bring it closer to the initial vision of it :upside_down_face: 
Your design 
![Screenshot from 2023-09-01 18-31-10](https://github.com/faisalakb/BookStore/assets/88894525/df7d9ffe-08aa-4390-973e-31c429b01dc8)

The zeplin design
![Screenshot from 2023-09-01 18-29-42](https://github.com/faisalakb/BookStore/assets/88894525/90754daf-1efa-4cd2-8e28-519b5fe4ce33)

2023-09-01 16:51 UTC, Alfredbis29 commented on src/App.css
>  .removeButton {
- [ ] I was not able to inline on the particular part where you designed this section add the new book, kindly follow the design guides, if we compare your design again here are not really similar :+1: 
 
Your Design 
![Screenshot from 2023-09-01 18-40-57](https://github.com/faisalakb/BookStore/assets/88894525/3013228a-7e48-4de4-bb6b-fe8f16ecf84f)

Zeplin Design to follow 
![Screenshot from 2023-09-01 18-41-51](https://github.com/faisalakb/BookStore/assets/88894525/0e55a06d-43e3-4b8e-95d4-85906a27c2c2)

2023-09-02 12:02 UTC, Alusp requested changes
Hi @faisalakb, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [ ] Linters set-up ✔️
- [ ] Commit messages descrptive ✔️
- [ ] Professional Github Flow used ✔️
- [ ] Professional PR Summary Flow used ✔️
- [ ] UI Closer to the given design :heavy_check_mark:  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 12:02 UTC, Alusp commented on src/App.css
>  }
- [ ] Good job in implementing the changes requested by the previous reviewer, however, according to the previous reviewer, you should ensure that your design matches the given requirement. as it is right now the contents of your `.inputContainer` class is overlapping each other, kindly align the margin properties of it contents.  Matching your design to the given design requirements enhances the chances of creating a successful and well-rounded design solution that meets the needs of users, complies with regulations, and performs effectively and efficiently. :slightly_smiling_face: 

Below is an illustration of yours and the given Design, please pay attention on the red markings on your design: :arrow_down: 

<table>
    <tr>
      <td>Your Design</td>
      <td>Given Design</td>
    </tr>
    <tr>
      <td>

![Student](https://github.com/faisalakb/BookStore/assets/43528594/a82dc64e-f5da-469a-9f2e-e2f46bd9fadd)


</td>
      <td>

![studesign](https://github.com/faisalakb/BookStore/assets/43528594/9d3212c0-81bb-41b7-82df-86612b89f5f6)

</td>
    </tr>
  </table>

2023-09-02 12:38 UTC, faisalakb commented
Please check, i updated the required changes said by the above reviewer.

2023-09-02 13:14 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @faisalakb👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented the changes requested by the previous reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-02 13:14 UTC, Johnadibe commented on src/component/BookDisplay.jsx
>            console.error('Error adding book:', error);
> - [OPTIONAL] It seems this wasn't noticed by the previous reviewer. I suggest you remove the console.error in your code, it makes your code look messy.😞

2023-09-02 13:14 UTC, Johnadibe commented on src/App.css
> +}
- [OPTIONAL] It seems the size of your button design doesn't align with the provided design. Please kindly ensure to fix that.👍

2023-09-02 13:16 UTC, faisalakb commented
Thanks for the time and suggestions.

2023-09-02 13:16 UTC, merged